In [1]:
import numpy as np

In [2]:
data1 = [6, 7.5 , 8, 0, 1]

In [3]:
arr1 = np.array(data1)

In [4]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [8]:
arr1.shape

(5,)

In [9]:
data2 = [[1,2,3,4],
        [5,6,7,8]]

In [10]:
arr2 = np.array(data2)

In [11]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr2.shape

(2, 4)

In [13]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.arange(0,15,3)

array([ 0,  3,  6,  9, 12])

In [23]:
arr1.dtype

dtype('float64')

In [24]:
arr2.dtype

dtype('int32')

In [25]:
arr = np.array([1,2,3,4,5], dtype=np.int64)

In [26]:
arr.dtype

dtype('int64')

In [27]:
float_arr = arr.astype(np.float64)

In [28]:
float_arr.dtype

dtype('float64')

In [29]:
arr1 = np.array([[1,2,3],[4,5,6]], dtype=np.float64)

In [30]:
arr2 = np.array([[7,8,9],[10,11,12]], dtype=np.float64)

In [32]:
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [34]:
7 /5 

1.4

In [37]:
np.matmul(arr1,np.transpose(arr2))

array([[ 50.,  68.],
       [122., 167.]])