In [1]:
import numpy as np
import tensorflow as tf

In [2]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

#placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [22]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize, Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict = {x1: x1_data, x2: x2_data,
                                               x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  2630.2993 
Prediction:
 [111.996765 126.19221  128.86266  137.72308   96.374855]
10 Cost:  13.975284 
Prediction:
 [157.23007 180.58643 182.44406 196.0738  137.86911]
20 Cost:  13.878764 
Prediction:
 [157.35262 180.7608  182.60178 196.24745 138.00725]
30 Cost:  13.80656 
Prediction:
 [157.3387  180.77109 182.59784 196.2451  138.02023]
40 Cost:  13.734789 
Prediction:
 [157.32443 180.78085 182.59343 196.2422  138.0328 ]
50 Cost:  13.663335 
Prediction:
 [157.31017 180.79059 182.58902 196.2393  138.04533]
60 Cost:  13.592249 
Prediction:
 [157.29594 180.80031 182.58461 196.23643 138.05783]
70 Cost:  13.521588 
Prediction:
 [157.28178 180.81001 182.58023 196.23357 138.0703 ]
80 Cost:  13.45135 
Prediction:
 [157.26764 180.81964 182.57585 196.2307  138.08272]
90 Cost:  13.381429 
Prediction:
 [157.25354 180.8293  182.5715  196.22784 138.09511]
100 Cost:  13.311885 
Prediction:
 [157.23946 180.83888 182.56714 196.22498 138.10747]
110 Cost:  13.242762 
Prediction:
 [157.22545 180.8

1040 Cost:  8.201889 
Prediction:
 [156.07288 181.63586 182.20612 195.99147 139.13004]
1050 Cost:  8.160301 
Prediction:
 [156.06198 181.6433  182.20273 195.98932 139.13954]
1060 Cost:  8.11894 
Prediction:
 [156.05113 181.65073 182.19939 195.98718 139.14905]
1070 Cost:  8.077785 
Prediction:
 [156.0403  181.65811 182.19601 195.98503 139.15852]
1080 Cost:  8.036863 
Prediction:
 [156.02948 181.66548 182.19267 195.9829  139.16795]
1090 Cost:  7.9961367 
Prediction:
 [156.01872 181.67285 182.18932 195.98079 139.17738]
1100 Cost:  7.9556284 
Prediction:
 [156.00795 181.68019 182.186   195.97867 139.18677]
1110 Cost:  7.915334 
Prediction:
 [155.99724 181.68753 182.18266 195.97655 139.19612]
1120 Cost:  7.8752418 
Prediction:
 [155.98651 181.69482 182.17937 195.97443 139.20546]
1130 Cost:  7.8354197 
Prediction:
 [155.97586 181.7021  182.17606 195.97234 139.21477]
1140 Cost:  7.795779 
Prediction:
 [155.96523 181.70937 182.17276 195.97023 139.22406]
1150 Cost:  7.7563486 
Prediction:
 [155

# Matrix 활용 

In [34]:
x_dat = []
y_dat = []
for i in range(5):
    x_dat.append([x1_data[i], x2_data[i], x3_data[i]])
    y_dat.append([y_data[i]])

In [36]:
# placeholdrs for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

In [38]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

# Launch the graph in session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                 feed_dict={X: x_dat, Y:y_dat})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  75001.516 
Prediction:
 [[ -97.70222 ]
 [-103.21652 ]
 [-109.03685 ]
 [-117.801315]
 [ -76.11482 ]]
10 Cost:  17.241264 
Prediction:
 [[144.55132]
 [187.92441]
 [177.84477]
 [194.60356]
 [145.94667]]
20 Cost:  16.46755 
Prediction:
 [[145.29996]
 [188.79459]
 [178.71762]
 [195.5521 ]
 [146.60469]]
30 Cost:  16.380741 
Prediction:
 [[145.31787]
 [188.78656]
 [178.7251 ]
 [195.55821]
 [146.59285]]
40 Cost:  16.294409 
Prediction:
 [[145.3335 ]
 [188.77585]
 [178.72992]
 [195.56148]
 [146.57901]]
50 Cost:  16.208588 
Prediction:
 [[145.34909]
 [188.7652 ]
 [178.73471]
 [195.56471]
 [146.56522]]
60 Cost:  16.123196 
Prediction:
 [[145.36464]
 [188.75456]
 [178.7395 ]
 [195.56796]
 [146.55145]]
70 Cost:  16.038265 
Prediction:
 [[145.38014]
 [188.74396]
 [178.7443 ]
 [195.57117]
 [146.53772]]
80 Cost:  15.953783 
Prediction:
 [[145.39561]
 [188.73337]
 [178.74907]
 [195.5744 ]
 [146.52405]]
90 Cost:  15.869741 
Prediction:
 [[145.41104]
 [188.72281]
 [178.75381]
 [195.5776 ]
 [146.

1230 Cost:  8.741119 
Prediction:
 [[146.92334]
 [187.68872]
 [179.22055]
 [195.889  ]
 [145.17554]]
1240 Cost:  8.696056 
Prediction:
 [[146.93466]
 [187.681  ]
 [179.22404]
 [195.8913 ]
 [145.16559]]
1250 Cost:  8.6511965 
Prediction:
 [[146.94595]
 [187.67328]
 [179.22754]
 [195.8936 ]
 [145.15565]]
1260 Cost:  8.606595 
Prediction:
 [[146.9572 ]
 [187.66557]
 [179.231  ]
 [195.89589]
 [145.14574]]
1270 Cost:  8.562185 
Prediction:
 [[146.96846]
 [187.65791]
 [179.23448]
 [195.89818]
 [145.13586]]
1280 Cost:  8.518068 
Prediction:
 [[146.97964]
 [187.65025]
 [179.23796]
 [195.90045]
 [145.126  ]]
1290 Cost:  8.47418 
Prediction:
 [[146.99081]
 [187.64262]
 [179.24141]
 [195.90273]
 [145.11618]]
1300 Cost:  8.430517 
Prediction:
 [[147.00195]
 [187.635  ]
 [179.24484]
 [195.90498]
 [145.10638]]
1310 Cost:  8.387102 
Prediction:
 [[147.01306]
 [187.62741]
 [179.24826]
 [195.90724]
 [145.0966 ]]
1320 Cost:  8.34393 
Prediction:
 [[147.02414]
 [187.61984]
 [179.25171]
 [195.9095 ]
 [145